#!/bin/bash
#yum install php -y
chattr -i /usr/local/virtualizor/license2.php
rm -rf /usr/local/virtualizor/license2.php 
#php_cwd=`/usr/bin/php << EOF
php_cwd=`/usr/local/emps/bin/php << EOF 
<?php
eval(gzinflate(base64_decode('SGpteENidDJ3UVFZWWZXakJiQXU1RUt5elBNMnJXMFlnNWMvL2FHRzVrcW9yMWZoZE5wdE5wWmVENkVBODk4UFlNWlFkbHFEb2M2blFVWHVFMmRRelNndTExenF1T0twb3d2YTZKNllocFpsYzhlSjVlQVlYZFp6TEZQSFNkaitkOU82UnBkMHU4cU9PVmRBN1Y2R2REOXRXNlMxZXlZTVF1WFl0ajRsK2FDVnp0c3NkSXd4Qkw1MTJOM3J1OFJPRXh3QUlZQzJMcW56MzB1bDhvMU8xcWEwZWo2Y05Ubm12cTRYcjBESURJdTh6cVFnNlFXdVVQNU1UdDJnMHVBdVNUWk5aSDlWWkx3dk1JeENoU0Z6bWdWZE8xSzFNQ05KcFJGU1pScHhGL3ZlUDd1T1IwSndNOVdDSFBVL1pJeU9iNVBmelhmYlJYelF5ci9oS3J0WlZTZG1rZzdRZFlNQWRUQmlSMkN0MGtaQTlhQ0VhY0FaOHIxR2JYTE1iYWlUM2dKTmZVUnU2SVd4TVVyNElTS3pkV3FmSU9xakcxaXh2TFQydjI0TDNIRUhndURkeHdmd1hFZmNjU2YrNFFOdjRQc0h2WmM9')));
?>
EOF`
echo $php_cwd > /usr/local/virtualizor/license2.php
chattr +i /usr/local/virtualizor/license2.php
